### ISSUE TITLE
Relative asset links are not resolved

### ISSUE THREAD

**Issue by drwelby** [radiantearth/stac-browser#108]
Our (Maxar) catalogs use relative links for assets:

https://radiantearth.github.io/stac-browser/#/external/ard.maxar.com/samples/v3/australia_vineyards/order_collections/5763006576028575312_root_collection.json

This breaks the download button and image preview by generating links to `https://radiantearth.github.io/<asset filename>`.

We have some Vue developers so I'll see if we can contribute a solution but I thought I'd report it in the meantime.

**Comment by drwelby** [comment]
Note this is the V3 branch, current master seems to be OK

**Comment by m-mohr** [comment]
Yep, that looks like a bug. I'll investigate and issue a fix asap. Shouldn't take too long. Thanks for reporting.

**Comment by drwelby** [comment]
We were just looking at it, but you might have it fixed before my laptop finishes upgrading `node` (assuming it doesn't catch fire first).

**Comment by m-mohr** [comment]
Thanks. I already found it, it's a simple fix. Can commit in 2mins or so.

**Comment by m-mohr** [comment]
Fix is available. Let me know when you still encounter issues.

**Comment by drwelby** [comment]
This is fixed for the download link, but seems to do something related in the Leaflet preview.

https://radiantearth.github.io/stac-browser/#/external/maxar-ard-samples.s3.amazonaws.com/v3/australia_vineyards/50/213133231011/2019-10-07/10500100191CD200.json

If you click on `Show` for the `Visual (RGB)` Asset and watch the requests, it looks like `stac-layer` is looking relative the Item URL:

https://maxar-ard-samples.s3.amazonaws.com/v3/australia_vineyards/50/213133231011/2019-10-07/10500100191CD200.json/10500100191CD200-clouds.tif

when the correct path would be:

https://maxar-ard-samples.s3.amazonaws.com/v3/australia_vineyards/50/213133231011/2019-10-07/10500100191CD200-clouds.tif

I'm not sure if this is coming from the browser or `stac-layer` yet but will investigate.

**Comment by m-mohr** [comment]
@drwelby Could be that stac-layer does it wrong, but to circumvent that I'm passing the absolute URL to stac-layer now so that we are "safe" in all cases. So should be fixed.

Visualization on the map is still not ideal due to the two "bboxes" shown in your example, but that's something for later. :-)

Let me know any other issues you encounter...

**Comment by drwelby** [comment]
Thanks Matthias for the quick fix, looks like next for us is to look at is getting `stac-layer` to render YCbCr COGs correctly...

**Comment by m-mohr** [comment]
Default behavior is to render COGs and if an error occurs instead fall back to the tile service. You can also enforce the tile service in the config. For more details I have to redirect you to the stac-layer repo.

Having YCbCr support in stac-layer directly would be nice, indeed. @DanielJDufour

**Comment by DanielJDufour** [comment]
Hi, guys.  YCbCR support would be great!  I created the issue above https://github.com/GeoTIFF/georaster-layer-for-leaflet/issues/88 to track this request.  Thanks!

**Comment by drwelby** [comment]
> You can also enforce the tile service in the config

Sorry, I can see how to specify template, but not how to force it. What's the config value I need to set?

**Comment by m-mohr** [comment]
@DanielJDufour Can you help? I'm pretty sure we discussed adding that option (to stac-layer) and I assumed it's there, but can't find it right now, too.

**Comment by DanielJDufour** [comment]
Hi, guys.  Sorry for the late reply.  I'll look at this now.

**Comment by m-mohr** [comment]
Also opened an issue for the "enforce tile server" option: https://github.com/stac-utils/stac-layer/issues/24

**Comment by DanielJDufour** [comment]
Relative URL option should be fixed with https://github.com/radiantearth/stac-browser/pull/110

**Comment by m-mohr** [comment]
> > You can also enforce the tile service in the config

@drwelby To clarify (I also updated the docs): To enforce using server-side rendering of imagery useTileLayerAsFallback must be set to false and either tileUrlTemplate or buildTileUrlTemplate must be given.

**Comment by DanielJDufour** [comment]
@drwelby  and @m-mohr , just a heads up that I just published a new version of stac-layer that includes the YCbCr support from georaster-layer-for-leaflet.
